language: python
python:
  - '3.6'
env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=py34
  - TOXENV=py36
  - TOXENV=pep8
before_install:
  - pip install -U coveralls pip pytest pytest-cov setuptools wheel tox
script:
  - tox
after_success:
  - coveralls
notifications:
  irc:
    channels: "irc.freenode.org#atal-dev"
    on_success: change
    on_failure: change
before_deploy:
- python setup.py build sdist bdist_wheel
- if [ "x" == "$(grep $(git tag -l --points-at=HEAD) setup.py)x" ]; then echo 'new tag does not exist in setup.py; bailing!'; exit 1; else echo "tag found in setup.py"; fi
deploy:
  - provider: pypi
    user: atal
    skip_cleanup: true
    distributions: "sdist bdist_wheel"
    password:
      secure: "TZgH3BkDt3p5ZSk7AciN/VQ/Vcj1NHK+HseQbW7R7AiHV+9cH3JiRazdldu6B6XiJtf4lfr6792h/aqbzchFaBtLdU21BhL42RGu4rqC5z5Jo7u8ljcEyj8A6RKDTHptrafZkLKSHi0J2IswIVE7Csq6nFkrf0cluEStU40vGus="
    on:
      tags: true
      repo: a-tal/ddate
      condition: $TOXENV = py36
  - provider: releases
    api_key:
      secure: "FiDh9oy0fwd3Mvo/Uo8OiAUA8K198e2s5BspB5wkDqaxqoJMCFAl/MytbeKjyNdeEfio3PeHwVGLR5295FjD8TS/TBbRGtb6cUg7iNAriWvfQlqXE1lEATEQW+IbCzR+Mz7BQJuQJ9cmbGV99PpU3gP0UeqNaSUAkAvt1x6sng0="
    file: "/home/travis/build/a-tal/ddate/dist/ddate*.whl"
    file_glob: true
    skip_cleanup: true
    on:
      tags: true
      condition: $TOXENV = py36
